Repository mendix/native-widgets, pull requests merged in 2023-10, with the labels that each got.

#74 [MOO-1159]: Add accessibility to Image
  packages/jsActions/mobile-resources-native/package.json
  packages/pluggableWidgets/column-chart-native/package.json
  packages/pluggableWidgets/image-native/CHANGELOG.md
  packages/pluggableWidgets/image-native/package.json
  packages/pluggableWidgets/image-native/src/Image.editorConfig.ts
  packages/pluggableWidgets/image-native/src/Image.tsx
  packages/pluggableWidgets/image-native/src/Image.xml
  packages/pluggableWidgets/image-native/src/components/BackgroundImage.tsx
  packages/pluggableWidgets/image-native/src/components/ImageComponents.tsx
  packages/pluggableWidgets/image-native/src/components/__tests__/Image.spec.tsx
  packages/pluggableWidgets/image-native/src/components/__tests__/__snapshots__/Image.spec.tsx.snap
  packages/pluggableWidgets/image-native/src/package.xml
  packages/pluggableWidgets/image-native/typings/ImageProps.d.ts
Labels: enhancement

#71 Native Mobile Resources: Updating changelogs
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
  packages/pluggableWidgets/column-chart-native/CHANGELOG.md
Labels: Widget

#70 Native Mobile Resources: Updating changelogs
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
Labels: Widget, Core

#79 Native Mobile Resources: Updating changelogs
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
  packages/pluggableWidgets/image-native/CHANGELOG.md
  packages/pluggableWidgets/image-native/typings/ImageProps.d.ts
Labels: Widget

#83 Nanoflow Commons: Updating changelogs
  packages/jsActions/mobile-resources-native/package.json
  packages/jsActions/nanoflow-actions-native/CHANGELOG.md
  packages/jsActions/nanoflow-actions-native/package.json
Labels: Widget

#86 Native Mobile Resources: Updating changelogs
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
  packages/jsActions/nanoflow-actions-native/package.json
  packages/pluggableWidgets/floating-action-button-native/CHANGELOG.md
Labels: Widget

#73 [MOO-1148] add push notification permission request support for Android API level>=33
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
Labels: Widget
