Repository mendix/native-widgets, pull requests merged in 2024-08, with the labels that each got.

#161 [MOO-1569]: Fix marketplace release pipeline (10.12)
  .gitignore
  scripts/automation/mxbuild.Dockerfile
  scripts/release/module-automation/commons.js
Labels: Core

#156 [MOO-1519]: fix request notification permission return value (9.24)
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
Labels: Widget

#159 [MOO-1569]: Fix marketplace release pipeline
  .gitignore
  packages/jsActions/nanoflow-actions-native/package.json
  scripts/automation/mxbuild.Dockerfile
  scripts/release/module-automation/commons.js
Labels: Widget, Core

#158 [MOO-1519]: fix request notification permission return value (10.12)
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
Labels: Widget

#157 [MOO-1519]: fix request notification permission return value (10.6)
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
Labels: Widget

#168 [MOO-1315]: Resolve issue with callout display on iOS
  packages/pluggableWidgets/maps-native/CHANGELOG.md
  packages/pluggableWidgets/maps-native/package.json
  packages/pluggableWidgets/maps-native/src/Maps.tsx
  packages/pluggableWidgets/maps-native/src/package.xml
  packages/pluggableWidgets/maps-native/src/util/data.ts
Labels: Widget

#141 [MOO-1469] react native upgrade to 0.73.8
  configs/e2e/native_dependencies.json
  package.json
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
  packages/pluggableWidgets/app-events-native/src/__tests__/AppEvents.spec.tsx
  packages/pluggableWidgets/bottom-sheet-native/CHANGELOG.md
  packages/pluggableWidgets/bottom-sheet-native/package.json
  packages/pluggableWidgets/bottom-sheet-native/src/__tests__/__snapshots__/BottomSheet.spec.tsx.snap
  packages/pluggableWidgets/bottom-sheet-native/src/package.xml
  packages/pluggableWidgets/feedback-native/src/__tests__/__snapshots__/Feedback.spec.tsx.snap
  packages/pluggableWidgets/gallery-native/CHANGELOG.md
  packages/pluggableWidgets/gallery-native/package.json
  packages/pluggableWidgets/gallery-native/src/components/Gallery.tsx
  packages/pluggableWidgets/gallery-native/src/components/__tests__/Gallery.spec.tsx
  packages/pluggableWidgets/gallery-native/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap
  packages/pluggableWidgets/gallery-native/src/package.xml
  packages/pluggableWidgets/intro-screen-native/CHANGELOG.md
  packages/pluggableWidgets/intro-screen-native/package.json
  packages/pluggableWidgets/intro-screen-native/src/SwipeableContainer.tsx
  packages/pluggableWidgets/intro-screen-native/src/__tests__/__snapshots__/IntroScreen.notch.spec.tsx.snap
  packages/pluggableWidgets/intro-screen-native/src/__tests__/__snapshots__/IntroScreen.spec.tsx.snap
  packages/pluggableWidgets/intro-screen-native/src/package.xml
  packages/pluggableWidgets/listview-swipe-native/CHANGELOG.md
  packages/pluggableWidgets/listview-swipe-native/package.json
  packages/pluggableWidgets/listview-swipe-native/src/package.xml
  packages/pluggableWidgets/popup-menu-native/src/__tests__/PopupMenu.spec.tsx
  packages/pluggableWidgets/rating-native/CHANGELOG.md
  packages/pluggableWidgets/rating-native/package.json
  packages/pluggableWidgets/rating-native/src/__test__/Rating.spec.tsx
  packages/pluggableWidgets/rating-native/src/package.xml
  packages/pluggableWidgets/signature-native/src/__tests__/__snapshots__/Signature.android.spec.tsx.snap
  packages/pluggableWidgets/signature-native/src/__tests__/__snapshots__/Signature.ios.spec.tsx.snap
  packages/pluggableWidgets/video-player-native/CHANGELOG.md
  packages/pluggableWidgets/video-player-native/package.json
  packages/pluggableWidgets/video-player-native/src/VideoPlayer.tsx
  packages/pluggableWidgets/video-player-native/src/__tests__/__snapshots__/VideoPlayer.spec.tsx.snap
  packages/pluggableWidgets/video-player-native/src/package.xml
  packages/pluggableWidgets/web-view-native/src/__tests__/__snapshots__/WebView.spec.tsx.snap
  patches/@mendix+pluggable-widgets-tools+9.24.1.patch
  patches/react-native-gesture-handler+2.16.2.patch
  yarn.lock
Labels: Widget

#154 [MOO-1519]: fix request notification permission return value
  .github/workflows/Build.yml
  .github/workflows/Release.yml
  .github/workflows/UnitTests.yml
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/src/notifications/RequestNotificationPermission.ts
Labels: Widget, Core

#171 Marketplace release pipeline
  .github/workflows/MarketplaceRelease.yml
  package.json
Labels: Core

#173 Update Min MX Version to 10.12.0.38909
  packages/jsActions/mobile-resources-native/package.json
  packages/jsActions/nanoflow-actions-native/package.json
Labels: Widget

#174 Update min mx version to 10.6.13 and update test app branch
  packages/jsActions/mobile-resources-native/package.json
  packages/jsActions/nanoflow-actions-native/package.json
Labels: Widget

#175 Update min mx version to 9.24.26 and update test app branch
  packages/jsActions/mobile-resources-native/package.json
  packages/jsActions/nanoflow-actions-native/package.json
Labels: Widget

#178 Native Mobile Resources: Updating changelogs
  packages/jsActions/mobile-resources-native/CHANGELOG.md
  packages/jsActions/mobile-resources-native/package.json
  packages/pluggableWidgets/maps-native/CHANGELOG.md
Labels: Widget, Core
